config-version: 1

mysql:
  enable: true
  host: localhost
  port: 3306
  database: 'server'
  username: '691422759'
  password: '1996612'
  table: 'test691422759'

shop:
  valid-time-in-mins: 7200

  max-sell-price: 100000
  min-sell-price: 0.1

  sell-limit: 8

  item-black-list:
    - BEDROCK
    - END_PORTAL_FRAME
    - SHULKER_BOX
    - WHITE_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIME_SHULKER_BOX
    - PINK_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - RED_SHULKER_BOX
    - BLACK_SHULKER_BOX